# Generated by Django 2.2.6 on 2020-11-04 11:20

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('app', '0002_accounts_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
